# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.transistor.v1 import transistor_pb2 as proto_dot_transistor_dot_v1_dot_transistor__pb2


class TransistorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Command = channel.unary_stream(
                '/transistor.v1.TransistorService/Command',
                request_serializer=proto_dot_transistor_dot_v1_dot_transistor__pb2.CommandRequest.SerializeToString,
                response_deserializer=proto_dot_transistor_dot_v1_dot_transistor__pb2.CommandResponse.FromString,
                )
        self.Publish = channel.stream_unary(
                '/transistor.v1.TransistorService/Publish',
                request_serializer=proto_dot_transistor_dot_v1_dot_transistor__pb2.PublishRequest.SerializeToString,
                response_deserializer=proto_dot_transistor_dot_v1_dot_transistor__pb2.PublishResponse.FromString,
                )
        self.Subscribe = channel.stream_stream(
                '/transistor.v1.TransistorService/Subscribe',
                request_serializer=proto_dot_transistor_dot_v1_dot_transistor__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=proto_dot_transistor_dot_v1_dot_transistor__pb2.SubscribeResponse.FromString,
                )


class TransistorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Command(self, request, context):
        """Open a new command line interface
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Publish(self, request_iterator, context):
        """Receive a stream from a non-cluster node
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request_iterator, context):
        """Receive a stream from both cluster/non-cluster nodes
        Always the subscriber should approach to this server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransistorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Command': grpc.unary_stream_rpc_method_handler(
                    servicer.Command,
                    request_deserializer=proto_dot_transistor_dot_v1_dot_transistor__pb2.CommandRequest.FromString,
                    response_serializer=proto_dot_transistor_dot_v1_dot_transistor__pb2.CommandResponse.SerializeToString,
            ),
            'Publish': grpc.stream_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=proto_dot_transistor_dot_v1_dot_transistor__pb2.PublishRequest.FromString,
                    response_serializer=proto_dot_transistor_dot_v1_dot_transistor__pb2.PublishResponse.SerializeToString,
            ),
            'Subscribe': grpc.stream_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=proto_dot_transistor_dot_v1_dot_transistor__pb2.SubscribeRequest.FromString,
                    response_serializer=proto_dot_transistor_dot_v1_dot_transistor__pb2.SubscribeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transistor.v1.TransistorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TransistorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Command(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/transistor.v1.TransistorService/Command',
            proto_dot_transistor_dot_v1_dot_transistor__pb2.CommandRequest.SerializeToString,
            proto_dot_transistor_dot_v1_dot_transistor__pb2.CommandResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Publish(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/transistor.v1.TransistorService/Publish',
            proto_dot_transistor_dot_v1_dot_transistor__pb2.PublishRequest.SerializeToString,
            proto_dot_transistor_dot_v1_dot_transistor__pb2.PublishResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/transistor.v1.TransistorService/Subscribe',
            proto_dot_transistor_dot_v1_dot_transistor__pb2.SubscribeRequest.SerializeToString,
            proto_dot_transistor_dot_v1_dot_transistor__pb2.SubscribeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
